runtime: nodejs10
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  min_pending_latency: 300ms

handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)

# basic_scaling:
#   max_instances: 1
#   idle_timeout: 5m