
runtime: nodejs12
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}