export const INIT_ANIVERSARIANTES = 'INIT_ANIVERSARIANTES';
export const FETCH_ANIVERSARIANTES_START = 'FETCH_ANIVERSARIANTES_START';
export const FETCH_ANIVERSARIANTES_SUCCESS = 'FETCH_ANIVERSARIANTES_SUCCESS';
export const FETCH_ANIVERSARIANTES_FAIL = 'FETCH_ANIVERSARIANTES_FAIL';
export const SET_MES_INFO = 'SET_MES_INFO';

export const INIT_AUTH = 'INIT_AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_CHECK_STATE_COMPLETE = 'AUTH_CHECK_STATE_COMPLETE';
export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_COMPLETE = 'AUTH_LOGOUT_COMPLETE';

export const INIT_PROPERTIES = 'INIT_PROPERTIES';

export const INIT_PESSOA_CADASTRO = 'INIT_PESSOA_CADASTRO';
export const PESSOA_CADASTRO_START = 'PESSOA_CADASTRO_START';
export const PESSOA_CADASTRO_SUCCESS = 'PESSOA_CADASTRO_SUCCESS';
export const PESSOA_CADASTRO_FAIL = 'PESSOA_CADASTRO_FAIL';

export const INIT_PESSOA_ATUALIZA = 'INIT_PESSOA_ATUALIZA';
export const PESSOA_ATUALIZA_START = 'PESSOA_ATUALIZA_START';
export const PESSOA_ATUALIZA_SUCCESS = 'PESSOA_ATUALIZA_SUCCESS';
export const PESSOA_ATUALIZA_FAIL = 'PESSOA_ATUALIZA_FAIL';

export const NOTIFICACOES_SUBSCREVE = 'NOTIFICACOES_SUBSCREVE';
