export const INIT_ANIVERSARIANTES = 'INIT_ANIVERSARIANTES';
export const FETCH_ANIVERSARIANTES_START = 'FETCH_ANIVERSARIANTES_START';
export const FETCH_ANIVERSARIANTES_SUCCESS = 'FETCH_ANIVERSARIANTES_SUCCESS';
export const FETCH_ANIVERSARIANTES_FAIL = 'FETCH_ANIVERSARIANTES_FAIL';
export const SET_MES_INFO = 'SET_MES_INFO';

export const INIT_AUTH = 'INIT_AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const CHECK_ID_FAMILIA = 'CHECK_ID_FAMILIA';
export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_COMPLETE = 'AUTH_LOGOUT_COMPLETE';

export const INIT_PROPERTIES = 'INIT_PROPERTIES';
