export const INIT_ANIVERSARIANTES = 'INIT_ANIVERSARIANTES';
export const SET_ANIVERSARIANTES = 'SET_ANIVERSARIANTES';
export const SET_ANIVERSARIANTES_DIA = 'GET_ANIVERSARIANTES_DIA';

export const SET_MES = 'SET_MES';
